dependencies:
 - python=3.6
 - numpy
 - scipy
 - scikit-learn
 - jupyter
 - requests
 - pandas
 - seaborn
 - click
 - openpyxl
 - pyyaml
 - cython
 - pip:
   - watermark
   - pytest
   - scikit-plot
   - nose
   - python-dotenv
